// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace DataDrivenFramework
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// MyFirstAssert - Use 'MyFirstAssertExpectedValues' to pass parameters into this method.
        /// </summary>
        public void MyFirstAssert()
        {
            #region Variable Declarations
            HtmlEdit uIUsername_showEdit = this.UIMSNcomHotmailOutlookWindow.UIAdactIncomSearchHoteDocument.UIUsername_showEdit;
            #endregion

            // Wait for 5 seconds for user delay between actions; Verify that the 'Text' property of 'username_show' text box equals 'Hello pocsgeza!'
            Playback.Wait(5000);
            Assert.AreEqual(this.MyFirstAssertExpectedValues.UIUsername_showEditText, uIUsername_showEdit.Text, "Incorrect username displayed");
        }
        
        #region Properties
        public virtual MyFirstAssertExpectedValues MyFirstAssertExpectedValues
        {
            get
            {
                if ((this.mMyFirstAssertExpectedValues == null))
                {
                    this.mMyFirstAssertExpectedValues = new MyFirstAssertExpectedValues();
                }
                return this.mMyFirstAssertExpectedValues;
            }
        }
        
        public UIMSNcomHotmailOutlookWindow UIMSNcomHotmailOutlookWindow
        {
            get
            {
                if ((this.mUIMSNcomHotmailOutlookWindow == null))
                {
                    this.mUIMSNcomHotmailOutlookWindow = new UIMSNcomHotmailOutlookWindow();
                }
                return this.mUIMSNcomHotmailOutlookWindow;
            }
        }
        #endregion
        
        #region Fields
        private MyFirstAssertExpectedValues mMyFirstAssertExpectedValues;
        
        private UIMSNcomHotmailOutlookWindow mUIMSNcomHotmailOutlookWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'MyFirstAssert'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class MyFirstAssertExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Wait for 5 seconds for user delay between actions; Verify that the 'Text' property of 'username_show' text box equals 'Hello pocsgeza!'
        /// </summary>
        public string UIUsername_showEditText = "Hello pocsgeza!";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNcomHotmailOutlookWindow : BrowserWindow
    {
        
        public UIMSNcomHotmailOutlookWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            this.WindowTitles.Add("AdactIn.com - Hotel Reservation System");
            this.WindowTitles.Add("AdactIn.com - Search Hotel");
            this.WindowTitles.Add("AdactIn.com - Select Hotel");
            this.WindowTitles.Add("AdactIn.com - Book A Hotel");
            this.WindowTitles.Add("AdactIn.com - Hotel Booking Confirmation");
            this.WindowTitles.Add("AdactIn.com - Logout");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMSNcomHotmailOutlookDocument UIMSNcomHotmailOutlookDocument
        {
            get
            {
                if ((this.mUIMSNcomHotmailOutlookDocument == null))
                {
                    this.mUIMSNcomHotmailOutlookDocument = new UIMSNcomHotmailOutlookDocument(this);
                }
                return this.mUIMSNcomHotmailOutlookDocument;
            }
        }
        
        public UIAdactIncomHotelReserDocument UIAdactIncomHotelReserDocument
        {
            get
            {
                if ((this.mUIAdactIncomHotelReserDocument == null))
                {
                    this.mUIAdactIncomHotelReserDocument = new UIAdactIncomHotelReserDocument(this);
                }
                return this.mUIAdactIncomHotelReserDocument;
            }
        }
        
        public UIAdactIncomSearchHoteDocument UIAdactIncomSearchHoteDocument
        {
            get
            {
                if ((this.mUIAdactIncomSearchHoteDocument == null))
                {
                    this.mUIAdactIncomSearchHoteDocument = new UIAdactIncomSearchHoteDocument(this);
                }
                return this.mUIAdactIncomSearchHoteDocument;
            }
        }
        
        public UIAdactIncomSelectHoteDocument UIAdactIncomSelectHoteDocument
        {
            get
            {
                if ((this.mUIAdactIncomSelectHoteDocument == null))
                {
                    this.mUIAdactIncomSelectHoteDocument = new UIAdactIncomSelectHoteDocument(this);
                }
                return this.mUIAdactIncomSelectHoteDocument;
            }
        }
        
        public UIAdactIncomBookAHotelDocument UIAdactIncomBookAHotelDocument
        {
            get
            {
                if ((this.mUIAdactIncomBookAHotelDocument == null))
                {
                    this.mUIAdactIncomBookAHotelDocument = new UIAdactIncomBookAHotelDocument(this);
                }
                return this.mUIAdactIncomBookAHotelDocument;
            }
        }
        
        public UIAdactIncomHotelBookiDocument UIAdactIncomHotelBookiDocument
        {
            get
            {
                if ((this.mUIAdactIncomHotelBookiDocument == null))
                {
                    this.mUIAdactIncomHotelBookiDocument = new UIAdactIncomHotelBookiDocument(this);
                }
                return this.mUIAdactIncomHotelBookiDocument;
            }
        }
        
        public UIMSNcomHotmailOutlookTitleBar UIMSNcomHotmailOutlookTitleBar
        {
            get
            {
                if ((this.mUIMSNcomHotmailOutlookTitleBar == null))
                {
                    this.mUIMSNcomHotmailOutlookTitleBar = new UIMSNcomHotmailOutlookTitleBar(this);
                }
                return this.mUIMSNcomHotmailOutlookTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIMSNcomHotmailOutlookDocument mUIMSNcomHotmailOutlookDocument;
        
        private UIAdactIncomHotelReserDocument mUIAdactIncomHotelReserDocument;
        
        private UIAdactIncomSearchHoteDocument mUIAdactIncomSearchHoteDocument;
        
        private UIAdactIncomSelectHoteDocument mUIAdactIncomSelectHoteDocument;
        
        private UIAdactIncomBookAHotelDocument mUIAdactIncomBookAHotelDocument;
        
        private UIAdactIncomHotelBookiDocument mUIAdactIncomHotelBookiDocument;
        
        private UIMSNcomHotmailOutlookTitleBar mUIMSNcomHotmailOutlookTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNcomHotmailOutlookDocument : HtmlDocument
    {
        
        public UIMSNcomHotmailOutlookDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/?ocid=iehp&pc=EUPP_";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            #endregion
        }
        
        #region Properties
        public UIMainCustom UIMainCustom
        {
            get
            {
                if ((this.mUIMainCustom == null))
                {
                    this.mUIMainCustom = new UIMainCustom(this);
                }
                return this.mUIMainCustom;
            }
        }
        
        public UIHeadercommonCustom UIHeadercommonCustom
        {
            get
            {
                if ((this.mUIHeadercommonCustom == null))
                {
                    this.mUIHeadercommonCustom = new UIHeadercommonCustom(this);
                }
                return this.mUIHeadercommonCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIMainCustom mUIMainCustom;
        
        private UIHeadercommonCustom mUIHeadercommonCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainCustom : HtmlCustom
    {
        
        public UIMainCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "main";
            this.SearchProperties["Id"] = "main";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"main\" role=\"main\" data-m=\'{\"i\":21,\"n";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIENTERTAINMENTCustom
        {
            get
            {
                if ((this.mUIENTERTAINMENTCustom == null))
                {
                    this.mUIENTERTAINMENTCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIENTERTAINMENTCustom.SearchProperties["TagName"] = "LI";
                    this.mUIENTERTAINMENTCustom.SearchProperties["Id"] = null;
                    this.mUIENTERTAINMENTCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIENTERTAINMENTCustom.FilterProperties["Class"] = "entertainment";
                    this.mUIENTERTAINMENTCustom.FilterProperties["ControlDefinition"] = "class=\"entertainment\" data-m=\'{\"i\":96,\"p";
                    this.mUIENTERTAINMENTCustom.FilterProperties["InnerText"] = "ENTERTAINMENT";
                    this.mUIENTERTAINMENTCustom.FilterProperties["TagInstance"] = "52";
                    this.mUIENTERTAINMENTCustom.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUIENTERTAINMENTCustom;
            }
        }
        
        public HtmlCustom UISkypeCustom
        {
            get
            {
                if ((this.mUISkypeCustom == null))
                {
                    this.mUISkypeCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUISkypeCustom.SearchProperties["TagName"] = "LI";
                    this.mUISkypeCustom.SearchProperties["Id"] = null;
                    this.mUISkypeCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUISkypeCustom.FilterProperties["Class"] = "integratedskype";
                    this.mUISkypeCustom.FilterProperties["ControlDefinition"] = "class=\"integratedskype\" role=\"presentati";
                    this.mUISkypeCustom.FilterProperties["InnerText"] = "Skype";
                    this.mUISkypeCustom.FilterProperties["TagInstance"] = "3";
                    this.mUISkypeCustom.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUISkypeCustom;
            }
        }
        
        public HtmlCustom UIActivisionstockOakleCustom
        {
            get
            {
                if ((this.mUIActivisionstockOakleCustom == null))
                {
                    this.mUIActivisionstockOakleCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIActivisionstockOakleCustom.SearchProperties["TagName"] = "LI";
                    this.mUIActivisionstockOakleCustom.SearchProperties["Id"] = null;
                    this.mUIActivisionstockOakleCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIActivisionstockOakleCustom.FilterProperties["Class"] = null;
                    this.mUIActivisionstockOakleCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIActivisionstockOakleCustom.FilterProperties["InnerText"] = "Activision stock Oakley banned? ";
                    this.mUIActivisionstockOakleCustom.FilterProperties["TagInstance"] = "109";
                    this.mUIActivisionstockOakleCustom.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUIActivisionstockOakleCustom;
            }
        }
        
        public HtmlHyperlink UISkypeHyperlink
        {
            get
            {
                if ((this.mUISkypeHyperlink == null))
                {
                    this.mUISkypeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISkypeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISkypeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISkypeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUISkypeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Skype";
                    this.mUISkypeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUISkypeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISkypeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.skype.com/";
                    this.mUISkypeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISkypeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://www.skype.com/\" target=\"_bl";
                    this.mUISkypeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUISkypeHyperlink.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUISkypeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIENTERTAINMENTCustom;
        
        private HtmlCustom mUISkypeCustom;
        
        private HtmlCustom mUIActivisionstockOakleCustom;
        
        private HtmlHyperlink mUISkypeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHeadercommonCustom : HtmlCustom
    {
        
        public UIHeadercommonCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "HEADER";
            this.SearchProperties["Id"] = "header-common";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "no-overlay";
            this.FilterProperties["ControlDefinition"] = "class=\"no-overlay\" id=\"header-common\" ro";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "UL";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAdactIncomHotelReserDocument : HtmlDocument
    {
        
        public UIAdactIncomHotelReserDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AdactIn.com - Hotel Reservation System";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/HotelApp/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://adactin.com/HotelApp/";
            this.WindowTitles.Add("AdactIn.com - Hotel Reservation System");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "username";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_input";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"username\" class=\"login_input\" id=\"";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUsernameEdit.WindowTitles.Add("AdactIn.com - Hotel Reservation System");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_input";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"password\" class=\"login_input\" id=\"";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("AdactIn.com - Hotel Reservation System");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlInputButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = "login";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = "login";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Login";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = "login_button";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"login\" class=\"login_button\" id=\"lo";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUILoginButton.WindowTitles.Add("AdactIn.com - Hotel Reservation System");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlInputButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAdactIncomSearchHoteDocument : HtmlDocument
    {
        
        public UIAdactIncomSearchHoteDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AdactIn.com - Search Hotel";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/HotelApp/SearchHotel.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://adactin.com/HotelApp/SearchHotel.php";
            this.WindowTitles.Add("AdactIn.com - Search Hotel");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UILocationComboBox
        {
            get
            {
                if ((this.mUILocationComboBox == null))
                {
                    this.mUILocationComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUILocationComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "location";
                    this.mUILocationComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "location";
                    this.mUILocationComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUILocationComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUILocationComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUILocationComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "9";
                    this.mUILocationComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "search_combobox";
                    this.mUILocationComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"location\" class=\"search_combobox\" ";
                    this.mUILocationComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUILocationComboBox.WindowTitles.Add("AdactIn.com - Search Hotel");
                    #endregion
                }
                return this.mUILocationComboBox;
            }
        }
        
        public HtmlComboBox UIRoom_nosComboBox
        {
            get
            {
                if ((this.mUIRoom_nosComboBox == null))
                {
                    this.mUIRoom_nosComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIRoom_nosComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "room_nos";
                    this.mUIRoom_nosComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "room_nos";
                    this.mUIRoom_nosComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIRoom_nosComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIRoom_nosComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIRoom_nosComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "11";
                    this.mUIRoom_nosComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "search_combobox";
                    this.mUIRoom_nosComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"room_nos\" class=\"search_combobox\" ";
                    this.mUIRoom_nosComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "4";
                    this.mUIRoom_nosComboBox.WindowTitles.Add("AdactIn.com - Search Hotel");
                    #endregion
                }
                return this.mUIRoom_nosComboBox;
            }
        }
        
        public HtmlComboBox UIAdult_roomComboBox
        {
            get
            {
                if ((this.mUIAdult_roomComboBox == null))
                {
                    this.mUIAdult_roomComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIAdult_roomComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "adult_room";
                    this.mUIAdult_roomComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "adult_room";
                    this.mUIAdult_roomComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIAdult_roomComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIAdult_roomComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIAdult_roomComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "5";
                    this.mUIAdult_roomComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "search_combobox";
                    this.mUIAdult_roomComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"adult_room\" class=\"search_combobox";
                    this.mUIAdult_roomComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "5";
                    this.mUIAdult_roomComboBox.WindowTitles.Add("AdactIn.com - Search Hotel");
                    #endregion
                }
                return this.mUIAdult_roomComboBox;
            }
        }
        
        public HtmlInputButton UISearchButton
        {
            get
            {
                if ((this.mUISearchButton == null))
                {
                    this.mUISearchButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "Submit";
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Submit";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Search";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "reg_button";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Submit\" class=\"reg_button\" id=\"Sub";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "4";
                    this.mUISearchButton.WindowTitles.Add("AdactIn.com - Search Hotel");
                    #endregion
                }
                return this.mUISearchButton;
            }
        }
        
        public HtmlEdit UIUsername_showEdit
        {
            get
            {
                if ((this.mUIUsername_showEdit == null))
                {
                    this.mUIUsername_showEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsername_showEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "username_show";
                    this.mUIUsername_showEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "username_show";
                    this.mUIUsername_showEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUsername_showEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsername_showEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsername_showEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "input_show";
                    this.mUIUsername_showEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"username_show\" class=\"input_show\" ";
                    this.mUIUsername_showEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUsername_showEdit.WindowTitles.Add("AdactIn.com - Search Hotel");
                    #endregion
                }
                return this.mUIUsername_showEdit;
            }
        }
        
        public HtmlInputButton UIResetButton
        {
            get
            {
                if ((this.mUIResetButton == null))
                {
                    this.mUIResetButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIResetButton.SearchProperties[HtmlButton.PropertyNames.Id] = "Reset";
                    this.mUIResetButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Reset";
                    this.mUIResetButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Reset";
                    this.mUIResetButton.FilterProperties[HtmlButton.PropertyNames.Type] = "reset";
                    this.mUIResetButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIResetButton.FilterProperties[HtmlButton.PropertyNames.Class] = "reg_button";
                    this.mUIResetButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Reset\" class=\"reg_button\" id=\"Rese";
                    this.mUIResetButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUIResetButton.WindowTitles.Add("AdactIn.com - Search Hotel");
                    #endregion
                }
                return this.mUIResetButton;
            }
        }
        
        public UISearch_formCustom UISearch_formCustom
        {
            get
            {
                if ((this.mUISearch_formCustom == null))
                {
                    this.mUISearch_formCustom = new UISearch_formCustom(this);
                }
                return this.mUISearch_formCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUILocationComboBox;
        
        private HtmlComboBox mUIRoom_nosComboBox;
        
        private HtmlComboBox mUIAdult_roomComboBox;
        
        private HtmlInputButton mUISearchButton;
        
        private HtmlEdit mUIUsername_showEdit;
        
        private HtmlInputButton mUIResetButton;
        
        private UISearch_formCustom mUISearch_formCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISearch_formCustom : HtmlCustom
    {
        
        public UISearch_formCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "search_form";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "search_form";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "name=\"search_form\" id=\"search_form\" onsu";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("AdactIn.com - Search Hotel");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Search Hotel (Fields marked with Red ast";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "width=\"100%\" class=\"login\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "10";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "login";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("AdactIn.com - Search Hotel");
            #endregion
        }
        
        #region Properties
        public HtmlCell UISearchHotelFieldsmarCell
        {
            get
            {
                if ((this.mUISearchHotelFieldsmarCell == null))
                {
                    this.mUISearchHotelFieldsmarCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUISearchHotelFieldsmarCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUISearchHotelFieldsmarCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUISearchHotelFieldsmarCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUISearchHotelFieldsmarCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Search Hotel (Fields marked with Red ast";
                    this.mUISearchHotelFieldsmarCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"login_title\" colspan=\"2\"";
                    this.mUISearchHotelFieldsmarCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUISearchHotelFieldsmarCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUISearchHotelFieldsmarCell.FilterProperties[HtmlCell.PropertyNames.Class] = "login_title";
                    this.mUISearchHotelFieldsmarCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "13";
                    this.mUISearchHotelFieldsmarCell.WindowTitles.Add("AdactIn.com - Search Hotel");
                    #endregion
                }
                return this.mUISearchHotelFieldsmarCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUISearchHotelFieldsmarCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAdactIncomSelectHoteDocument : HtmlDocument
    {
        
        public UIAdactIncomSelectHoteDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AdactIn.com - Select Hotel";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/HotelApp/SelectHotel.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://adactin.com/HotelApp/SelectHotel.php";
            this.WindowTitles.Add("AdactIn.com - Select Hotel");
            #endregion
        }
        
        #region Properties
        public HtmlRadioButton UIRadiobutton_2RadioButton
        {
            get
            {
                if ((this.mUIRadiobutton_2RadioButton == null))
                {
                    this.mUIRadiobutton_2RadioButton = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUIRadiobutton_2RadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "radiobutton_2";
                    this.mUIRadiobutton_2RadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "radiobutton_2";
                    this.mUIRadiobutton_2RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "2";
                    this.mUIRadiobutton_2RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = null;
                    this.mUIRadiobutton_2RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIRadiobutton_2RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "1";
                    this.mUIRadiobutton_2RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = null;
                    this.mUIRadiobutton_2RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"radiobutton_2\" id=\"radiobutton_2\" ";
                    this.mUIRadiobutton_2RadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "12";
                    this.mUIRadiobutton_2RadioButton.WindowTitles.Add("AdactIn.com - Select Hotel");
                    #endregion
                }
                return this.mUIRadiobutton_2RadioButton;
            }
        }
        
        public HtmlInputButton UIContinueButton
        {
            get
            {
                if ((this.mUIContinueButton == null))
                {
                    this.mUIContinueButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIContinueButton.SearchProperties[HtmlButton.PropertyNames.Id] = "continue";
                    this.mUIContinueButton.SearchProperties[HtmlButton.PropertyNames.Name] = "continue";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Continue";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.Class] = "reg_button";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"continue\" class=\"reg_button\" id=\"c";
                    this.mUIContinueButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "42";
                    this.mUIContinueButton.WindowTitles.Add("AdactIn.com - Select Hotel");
                    #endregion
                }
                return this.mUIContinueButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlRadioButton mUIRadiobutton_2RadioButton;
        
        private HtmlInputButton mUIContinueButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAdactIncomBookAHotelDocument : HtmlDocument
    {
        
        public UIAdactIncomBookAHotelDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AdactIn.com - Book A Hotel";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/HotelApp/BookHotel.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://adactin.com/HotelApp/BookHotel.php";
            this.WindowTitles.Add("AdactIn.com - Book A Hotel");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIFirst_nameEdit
        {
            get
            {
                if ((this.mUIFirst_nameEdit == null))
                {
                    this.mUIFirst_nameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirst_nameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "first_name";
                    this.mUIFirst_nameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "first_name";
                    this.mUIFirst_nameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIFirst_nameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirst_nameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirst_nameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "reg_input";
                    this.mUIFirst_nameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"first_name\" class=\"reg_input\" id=\"";
                    this.mUIFirst_nameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "11";
                    this.mUIFirst_nameEdit.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUIFirst_nameEdit;
            }
        }
        
        public HtmlEdit UILast_nameEdit
        {
            get
            {
                if ((this.mUILast_nameEdit == null))
                {
                    this.mUILast_nameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILast_nameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "last_name";
                    this.mUILast_nameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "last_name";
                    this.mUILast_nameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILast_nameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILast_nameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILast_nameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "reg_input";
                    this.mUILast_nameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"last_name\" class=\"reg_input\" id=\"l";
                    this.mUILast_nameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "12";
                    this.mUILast_nameEdit.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUILast_nameEdit;
            }
        }
        
        public HtmlTextArea UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new HtmlTextArea(this);
                    #region Search Criteria
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "address";
                    this.mUIAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "address";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "txtarea";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"address\" class=\"txtarea\" id=\"addre";
                    this.mUIAddressEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIAddressEdit.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUIAddressEdit;
            }
        }
        
        public HtmlEdit UICc_numEdit
        {
            get
            {
                if ((this.mUICc_numEdit == null))
                {
                    this.mUICc_numEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICc_numEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cc_num";
                    this.mUICc_numEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "cc_num";
                    this.mUICc_numEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICc_numEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICc_numEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICc_numEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "reg_input";
                    this.mUICc_numEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"cc_num\" class=\"reg_input\" id=\"cc_n";
                    this.mUICc_numEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "13";
                    this.mUICc_numEdit.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUICc_numEdit;
            }
        }
        
        public HtmlComboBox UICc_typeComboBox
        {
            get
            {
                if ((this.mUICc_typeComboBox == null))
                {
                    this.mUICc_typeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICc_typeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "cc_type";
                    this.mUICc_typeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "cc_type";
                    this.mUICc_typeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUICc_typeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICc_typeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICc_typeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "5";
                    this.mUICc_typeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "select_combobox";
                    this.mUICc_typeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"cc_type\" class=\"select_combobox\" i";
                    this.mUICc_typeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUICc_typeComboBox.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUICc_typeComboBox;
            }
        }
        
        public HtmlComboBox UICc_exp_monthComboBox
        {
            get
            {
                if ((this.mUICc_exp_monthComboBox == null))
                {
                    this.mUICc_exp_monthComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICc_exp_monthComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "cc_exp_month";
                    this.mUICc_exp_monthComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "cc_exp_month";
                    this.mUICc_exp_monthComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUICc_exp_monthComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICc_exp_monthComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICc_exp_monthComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "13";
                    this.mUICc_exp_monthComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "select_combobox2";
                    this.mUICc_exp_monthComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"cc_exp_month\" class=\"select_combob";
                    this.mUICc_exp_monthComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "2";
                    this.mUICc_exp_monthComboBox.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUICc_exp_monthComboBox;
            }
        }
        
        public UIBook_hotel_formCustom UIBook_hotel_formCustom
        {
            get
            {
                if ((this.mUIBook_hotel_formCustom == null))
                {
                    this.mUIBook_hotel_formCustom = new UIBook_hotel_formCustom(this);
                }
                return this.mUIBook_hotel_formCustom;
            }
        }
        
        public HtmlComboBox UICc_exp_yearComboBox
        {
            get
            {
                if ((this.mUICc_exp_yearComboBox == null))
                {
                    this.mUICc_exp_yearComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICc_exp_yearComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "cc_exp_year";
                    this.mUICc_exp_yearComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "cc_exp_year";
                    this.mUICc_exp_yearComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUICc_exp_yearComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICc_exp_yearComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICc_exp_yearComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "13";
                    this.mUICc_exp_yearComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "select_combobox2";
                    this.mUICc_exp_yearComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"cc_exp_year\" class=\"select_combobo";
                    this.mUICc_exp_yearComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "3";
                    this.mUICc_exp_yearComboBox.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUICc_exp_yearComboBox;
            }
        }
        
        public HtmlEdit UICc_cvvEdit
        {
            get
            {
                if ((this.mUICc_cvvEdit == null))
                {
                    this.mUICc_cvvEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICc_cvvEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cc_cvv";
                    this.mUICc_cvvEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "cc_cvv";
                    this.mUICc_cvvEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICc_cvvEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICc_cvvEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICc_cvvEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "reg_input";
                    this.mUICc_cvvEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"cc_cvv\" class=\"reg_input\" id=\"cc_c";
                    this.mUICc_cvvEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "14";
                    this.mUICc_cvvEdit.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUICc_cvvEdit;
            }
        }
        
        public HtmlInputButton UIBookNowButton
        {
            get
            {
                if ((this.mUIBookNowButton == null))
                {
                    this.mUIBookNowButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIBookNowButton.SearchProperties[HtmlButton.PropertyNames.Id] = "book_now";
                    this.mUIBookNowButton.SearchProperties[HtmlButton.PropertyNames.Name] = "book_now";
                    this.mUIBookNowButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Book Now";
                    this.mUIBookNowButton.FilterProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIBookNowButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIBookNowButton.FilterProperties[HtmlButton.PropertyNames.Class] = "reg_button";
                    this.mUIBookNowButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"book_now\" class=\"reg_button\" id=\"b";
                    this.mUIBookNowButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "15";
                    this.mUIBookNowButton.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUIBookNowButton;
            }
        }
        
        public HtmlEdit UIHotel_name_disEdit
        {
            get
            {
                if ((this.mUIHotel_name_disEdit == null))
                {
                    this.mUIHotel_name_disEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIHotel_name_disEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "hotel_name_dis";
                    this.mUIHotel_name_disEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "hotel_name_dis";
                    this.mUIHotel_name_disEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIHotel_name_disEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIHotel_name_disEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIHotel_name_disEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "disable_text";
                    this.mUIHotel_name_disEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"hotel_name_dis\" disabled=\"disabled";
                    this.mUIHotel_name_disEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIHotel_name_disEdit.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUIHotel_name_disEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIFirst_nameEdit;
        
        private HtmlEdit mUILast_nameEdit;
        
        private HtmlTextArea mUIAddressEdit;
        
        private HtmlEdit mUICc_numEdit;
        
        private HtmlComboBox mUICc_typeComboBox;
        
        private HtmlComboBox mUICc_exp_monthComboBox;
        
        private UIBook_hotel_formCustom mUIBook_hotel_formCustom;
        
        private HtmlComboBox mUICc_exp_yearComboBox;
        
        private HtmlEdit mUICc_cvvEdit;
        
        private HtmlInputButton mUIBookNowButton;
        
        private HtmlEdit mUIHotel_name_disEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBook_hotel_formCustom : HtmlCustom
    {
        
        public UIBook_hotel_formCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "book_hotel_form";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "book_hotel_form";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "name=\"book_hotel_form\" id=\"book_hotel_fo";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("AdactIn.com - Book A Hotel");
            #endregion
        }
        
        #region Properties
        public UIItemTable1 UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable1(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable1 mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTable1 : HtmlTable
    {
        
        public UIItemTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Back\r\nBook A Hotel \r\nHotel Name \r\nLocati";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "width=\"100%\" class=\"login\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "19";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "login";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("AdactIn.com - Book A Hotel");
            #endregion
        }
        
        #region Properties
        public HtmlCell UISelectMonthJanuaryFeCell
        {
            get
            {
                if ((this.mUISelectMonthJanuaryFeCell == null))
                {
                    this.mUISelectMonthJanuaryFeCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUISelectMonthJanuaryFeCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUISelectMonthJanuaryFeCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUISelectMonthJanuaryFeCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUISelectMonthJanuaryFeCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "- Select Month - January February March ";
                    this.mUISelectMonthJanuaryFeCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUISelectMonthJanuaryFeCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "16";
                    this.mUISelectMonthJanuaryFeCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUISelectMonthJanuaryFeCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUISelectMonthJanuaryFeCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "44";
                    this.mUISelectMonthJanuaryFeCell.WindowTitles.Add("AdactIn.com - Book A Hotel");
                    #endregion
                }
                return this.mUISelectMonthJanuaryFeCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUISelectMonthJanuaryFeCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAdactIncomHotelBookiDocument : HtmlDocument
    {
        
        public UIAdactIncomHotelBookiDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "AdactIn.com - Hotel Booking Confirmation";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/HotelApp/BookingConfirm.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://adactin.com/HotelApp/BookingConfirm.php";
            this.WindowTitles.Add("AdactIn.com - Hotel Booking Confirmation");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILogoutHyperlink
        {
            get
            {
                if ((this.mUILogoutHyperlink == null))
                {
                    this.mUILogoutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/HotelApp/Logout.php";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://adactin.com/HotelApp/Logout.php";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"Logout.php\"";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUILogoutHyperlink.WindowTitles.Add("AdactIn.com - Hotel Booking Confirmation");
                    #endregion
                }
                return this.mUILogoutHyperlink;
            }
        }
        
        public HtmlEdit UIOrder_noEdit
        {
            get
            {
                if ((this.mUIOrder_noEdit == null))
                {
                    this.mUIOrder_noEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIOrder_noEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "order_no";
                    this.mUIOrder_noEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "order_no";
                    this.mUIOrder_noEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIOrder_noEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIOrder_noEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIOrder_noEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "disable_text";
                    this.mUIOrder_noEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"order_no\" disabled=\"disabled\" clas";
                    this.mUIOrder_noEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "16";
                    this.mUIOrder_noEdit.WindowTitles.Add("AdactIn.com - Hotel Booking Confirmation");
                    #endregion
                }
                return this.mUIOrder_noEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILogoutHyperlink;
        
        private HtmlEdit mUIOrder_noEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNcomHotmailOutlookTitleBar : WinTitleBar
    {
        
        public UIMSNcomHotmailOutlookTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MSN.com - Hotmail, Outlook, Skype, Bing, Latest News, Photos & Videos");
            this.WindowTitles.Add("AdactIn.com - Logout");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("AdactIn.com - Logout");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
